build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
    - ''
  script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}
    | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - echo /kaniko/executor --cache=true --cache-repo=$CI_REGISTRY_IMAGE/cache --use-new-run
    --context . --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE
  - "/kaniko/executor --cache=true --cache-repo=$CI_REGISTRY_IMAGE/cache --use-new-run
    --context . --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE"
include:
- template: Security/Secret-Detection.gitlab-ci.yml
